name: Cats 😺

on:
  pull_request:
    types: [opened, reopened]

jobs:
  thank-you:
    name: A cat for your effort!
    runs-on: ubuntu-latest
    steps:
      - uses: ruairidhwm/action-cats@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.github_token }}